# Generated by Django 2.1.2 on 2018-11-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynowapp', '0006_auto_20181106_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderDetails',
        ),
    ]
