# Generated by Django 2.1.2 on 2018-11-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynowapp', '0008_auto_20181107_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverynowapp.Restaurant'),
        ),
    ]
