# Generated by Django 2.1.2 on 2018-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynowapp', '0009_auto_20181107_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
