# Generated by Django 2.1.2 on 2018-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynowapp', '0010_auto_20181113_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
